server:
  port: 8010
spring:
  servlet:
    multipart:
      max-file-size: 50MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/attia
    username: attia
    password: attia
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect





