spring:
  config:
    import: optional:configserver:http://localhost:8888
  stripe:
    secret-key: sk_test_51QCAHpBDW3LkkcbKFv9eNqLWddEC9JLkjAoZkB6VC6e52cHjojXS5vlEoWlZQWCeeAaN67bpZllUrR9RWehULuup00lCYHx3bX
  application:
    name: payment-service
