server:
  port: 8010
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: event-service
application:
  file:
    upload:
      photos-output-path: ./uploads






